Numpy高级应用

In [1]:
import numpy as np
import pandas as pd

np.ones((3,4,5), dtype=np.float64).strides

In [23]:
# reshape将一维数组转换为多维数组，ravel相反
arr=np.arange(15).reshape((5,-1))
arr.ravel('F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [26]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# 连接
np.concatenate([arr1, arr2], axis=0)
np.vstack((arr1, arr2))
np.hstack((arr1, arr2))

# 拆分
arr = np.random.randn(5, 2)
first, second, third = np.split(arr, [1, 3])
first

array([[-0.0092858 , -0.40937084]])

In [33]:
# 重复
arr = np.arange(3)
arr.repeat(3)
arr.repeat([2, 3, 4])

arr1 = np.random.randn(2, 2)
arr1.repeat(2, axis=0)
arr1.repeat([2, 3], axis=0)
arr1.repeat([2, 3], axis=1)

np.tile(arr1, 2)
np.tile(arr1, (2, 1))

array([[-1.5333822 , -0.72351348],
       [-1.73611164,  0.51135964],
       [-1.5333822 , -0.72351348],
       [-1.73611164,  0.51135964]])