# Numpy

In [2]:
import numpy as np
data=np.random.randn(2,3)
data

array([[-0.55587479, -0.26886115,  2.41131333],
       [-0.74760025, -1.5951533 ,  2.0892355 ]])

In [8]:
data*10
data.shape
data.dtype

dtype('float64')

In [29]:
np.eye(3)
# np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
# 数组切片是原始数组的视图，这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上
arr=np.arange(10)
arr[5:8]=12
arr
arr_slice = arr[5:8]         #明确地进行复制 arr[5:8].copy()
arr_slice[1]=456
arr
arr_slice[:]=789
arr

array([  0,   1,   2,   3,   4, 789, 789, 789,   8,   9])

In [90]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
names.size

7

In [99]:
# 花式索引返回的是一个一维数组，其中的元素对应各个索引元组；跟切片不一样，它总是将数据复制到新数组中。
arr=np.arange(32).reshape((8,4))
arr[[1, 5, 7, 2],[0, 3, 1, 2]]
# arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [181]:
# 数组转置返回的是源数据的视图（不会进行任何复制操作）
arr=np.arange(15).reshape((3,5))
arr
# 轴对换：
arr.T
# 计算矩阵内积：
# np.dot(arr,arr.T)
# np.dot(arr.T,arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [109]:
np.add(([[1,2],[3,4]]),([[5,6],[7,8]]))

array([[ 6,  8],
       [10, 12]])

In [140]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
# [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
%time np.where(cond,xarr,yarr)     #%timeit

Wall time: 0 ns


array([1.1, 2.2, 1.3, 1.4, 2.5])

In [165]:
arr=np.array([[ 0.6033, 1.2636, -0.2555],
[-0.4457, 0.4684, -0.9616],
[-1.8245, 0.6254, 1.0229],
[ 1.1074, 0.0909, -0.3501],
[ 0.218 , -0.8948, -1.7415]])
arr.sort(1)     #按行排序
arr

array([[-1.8245, -0.8948, -1.7415],
       [-0.4457,  0.0909, -0.9616],
       [ 0.218 ,  0.4684, -0.3501],
       [ 0.6033,  0.6254, -0.2555],
       [ 1.1074,  1.2636,  1.0229]])

In [182]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x.dot(np.ones(3))

array([ 6., 15.])

In [186]:
a1=np.array([1,2,3])
np.mat(a1)

matrix([[1, 2, 3]])

In [199]:
np.random.rand(10)

array([0.55776083, 0.96583653, 0.1471569 , 0.029647  , 0.59389349,
       0.1140657 , 0.95080985, 0.32570741, 0.19361869, 0.45781165])

In [204]:
nwalks = 5000
nsteps = 1000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)
walks

array([[  1,   0,  -1, ...,  76,  75,  74],
       [ -1,  -2,  -1, ...,  32,  31,  30],
       [  1,   2,   1, ...,  22,  21,  20],
       ...,
       [ -1,   0,   1, ...,  30,  29,  30],
       [  1,   2,   3, ...,  46,  47,  46],
       [  1,   2,   3, ..., -22, -23, -24]], dtype=int32)

In [245]:
walks.max()
walks.min()
walks.size

5000000

In [301]:
hits30=(np.abs(walks)>=30).any(1)
hits30.sum()

3435

In [292]:
crossing_time=(np.abs(walks[hits30])>=30).argmax(1)
print('均值:',crossing_time.mean())
print('方差:',crossing_time.var())      
print('标准差:',crossing_time.std())      
print('中值:',np.median(crossing_time)) 

均值: 496.2826783114993
方差: 57062.12999107992
标准差: 238.87680923664382
中值: 469.0
