In [16]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 0.39458996, -0.46678906,  0.28928277],
       [-1.91267851, -1.31404576,  0.40973596]])

In [3]:
data * 10

array([[-10.74496823,  18.24440593,  17.42503315],
       [  9.03149452,  -2.75350223,   7.79221617]])

In [4]:
data.dtype

dtype('float64')

In [5]:
data.shape

(2, 3)

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [21]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [3]:
7//2
# 7%2

3

-----参数定义的顺序必须是：必选参数、默认参数、可变参数、命名关键字参数和关键字参数-----

In [42]:
import math
#必选参数在前，默认参数在后；angle=0是默认参数，调用move时可不加angle参数
def move(x,y,step,angle=0):  
    nx=x+step*math.cos(angle)
    ny=y-step*math.sin(angle)
    return nx,ny             # Python的函数返回多值其实就是返回一个tuple
r = move(100, 100, 60, math.pi / 6)
r

(151.96152422706632, 70.0)

In [53]:
# 可变参数 *args
# 求平方和
def calc(*nums):
    sum=0
    for n in nums:
        sum+=n**2
    return sum
nums=[1,2,3]
calc(*nums)

14

In [56]:
# 关键字参数 **kw，kw接收的是一个dict
def person(name, age, **kw):
    print('name:', name, 'age:', age, 'other:', kw)
extra={'city':'shanghai','job':'engineer'}
person('martin','27',**extra)

name: martin age: 27 other: {'city': 'shanghai', 'job': 'engineer'}


In [73]:
# 命名关键字参数，限制关键字参数的名字；命名关键字参数需要一个特殊分隔符*，*后面的参数被视为命名关键字参数
def person(name, age, *, city, job):
    print(name, age, city, job)
person('Jack', 24, city='Beijing', job='Engineer')   #命名关键字参数必须传入参数名，如果没有传入参数名，调用将报错

# 函数定义中已经有了一个可变参数，后面跟着的命名关键字参数就不再需要一个特殊分隔符*了
# def person(name, age, *args, city, job)

Jack 24 Beijing Engineer


In [75]:
# 对于任意函数，都可以通过类似func(*args, **kw)的形式调用它
def f1(a, b, c=0, *args, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'args =', args, 'kw =', kw)

def f2(a, b, c=0, *, d, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'd =', d, 'kw =', kw)
args = (1, 2, 3, 4)
kw = {'d': 99, 'x': '#'}
f1(*args, **kw)
args = (1, 2, 3)
kw = {'d': 88, 'x': '#'}
f2(*args, **kw)

a = 1 b = 2 c = 3 args = (4,) kw = {'d': 99, 'x': '#'}
a = 1 b = 2 c = 3 d = 88 kw = {'x': '#'}


In [82]:
# 递归函数，一个函数在内部调用自身本身
# 尾递归优化，主要是要把每一步的乘积传入到递归函数中，栈不会增长，无论多少次调用也不会导致栈溢出。
# 计算阶乘
def fact(n):
    return fact_iter(n, 1)

def fact_iter(num, product):
    if num == 1:
        return product
    return fact_iter(num - 1, num * product)
fact(5)

120

In [41]:
# 求一元二次方程的解,ax2 + bx + c = 0
# import math
def quadratic(a,b,c):
    if a != 0:
        pd=b**2-4*a*c
        if (pd < 0):
            pass
        elif (pd == 0):
            x=-b / 2/a
            return x
        else:
            x1=(-b-math.sqrt(pd))/2/a
            x2=(-b+math.sqrt(pd))/2/a
            return (x1,x2)
    else:
        x=-c / b
        return x
x=quadratic(2,-7,6)
x

(1.5, 2.0)

In [83]:
# 生成器都是Iterator对象，但list、dict、str虽然是Iterable，却不是Iterator。
# 把list、dict、str等Iterable变成Iterator可以使用iter()函数：iter([1, 2, 3, 4, 5])
# map()函数接收两个参数，一个是函数，一个是Iterable，map将传入的函数依次作用到序列的每个元素，并把结果作为新的Iterator返回。
#map逐一遍历
a=[1,2,3]
b=map(lambda x:x+5,a)
list(b)

[6, 7, 8]

In [93]:
#reduce()递归计算
from functools import reduce
d=reduce(lambda x,y:x*y ,range(1,6))
d

120

In [95]:
#filter过滤器
c=filter(lambda x:x>3 , range(10))
list(c)

[4, 5, 6, 7, 8, 9]

-----正则表达式-----

In [104]:
import re
# 切分字符串
re.split(r'\s+', 'a b   c')
# 'a b   c'.split(' ')

['a', 'b', 'c']

In [105]:
# 分组()
m = re.match(r'^(\d{3})-(\d{3,8})$', '010-12345')
m.groups()
m.group(0)       #1,2

('010', '12345')